from typing import Protocol

from .models import *


class MessengerAdapter(Protocol):
    async def poll_events(self, cursor: str | None = None) -> list[InboundMessage]: ...
    async def prepare_send(self, command: AuthorizedSendCommand) -> SendOperation: ...
    async def commit_send(self, operation: SendOperation) -> SendOperation: ...
    async def verify_send(self, operation: SendOperation) -> SendOperation: ...


class ModelProvider(Protocol):
    async def plan(self, messages: list[Message]) -> ReplyPlan: ...
