"""Fail-closed QQ Live Driver building blocks.

Q0-Q3 are read-only. Q4-Q7 are intentionally not exported because their live
capabilities have not been implemented or certified.
"""

from .avatar_identity import (
    AvatarIdentityError,
    build_avatar_evidence,
    parse_avatar_report,
)
from .avatar_identity import (
    assess_pending_application as assess_avatar_pending_application,
)
from .environment import (
    CertifiedQQProfile,
    EnvironmentFingerprint,
    ModalState,
    QQEnvironmentSentinel,
    RuntimeDecision,
    RuntimeDecisionReason,
    RuntimeEnvelope,
    RuntimeSnapshot,
    WindowBounds,
    WindowPresentation,
)
from .front_half import (
    FrontHalfAssessment,
    FrontHalfNotReadyError,
    FrontHalfStatus,
    QQReadOnlyFrontHalf,
)
from .identity import (
    BindingAuditAction,
    BindingAuditEntry,
    BindingConflictError,
    BindingEvidenceAssessment,
    BindingEvidenceReason,
    BindingStatus,
    ConfirmationAction,
    ConversationBinding,
    ConversationType,
    HumanBindingConfirmation,
    IdentityBindingRegistry,
    IdentityDisposition,
    IdentityEvidenceSet,
    IdentityReason,
    IdentityResolution,
    assess_binding_evidence,
)
from .observation import (
    BoundObservationScope,
    ExactHwndCaptureCapabilities,
    ExactHwndReadonlyCapturePort,
    InMemoryObservationDedupStore,
    NormalizedInboundEventCandidate,
    ObservationBatch,
    ObservationDedupPort,
    ObservationDisposition,
    ObservationIssue,
    ObservationReason,
    ReadonlyMessageObserver,
    UnsafeCapturePortError,
    VisibleConversationSnapshot,
    VisibleDirection,
    VisibleMessage,
)
from .probe_bridge import ProbeBridgeError, ingest_probe_report
from .profile_identity import (
    ProfileIdentityError,
    assess_pending_application,
    build_identity_evidence,
    parse_profile_report,
)
from .session_lease import (
    LeaseAuditAction,
    LeaseAuditEntry,
    LeaseChallenge,
    LeaseStatus,
    LiveSessionScope,
    SessionLease,
    SessionLeaseError,
    SessionLeaseManager,
    SessionLeaseReason,
)
from .session_scope import (
    CurrentSessionInspectionError,
    CurrentSessionSnapshot,
    invoke_current_session_helper,
    parse_current_session_report,
)
from .topology import (
    CompiledSelector,
    MappingStatus,
    Q1SelectorPack,
    RoleCandidate,
    RoleMapping,
    SelectorCompileResult,
    SelectorRole,
    UiNodeInput,
    UiNodeSnapshot,
    UiTopologySnapshot,
    compile_selector_pack,
    map_role_candidates,
)
from .uia_capture import QQCurrentChatCapturePort, UiaCaptureError

__all__ = [
    "AvatarIdentityError",
    "BindingAuditAction",
    "BindingAuditEntry",
    "BindingConflictError",
    "BindingEvidenceAssessment",
    "BindingEvidenceReason",
    "BindingStatus",
    "BoundObservationScope",
    "CertifiedQQProfile",
    "CompiledSelector",
    "ConfirmationAction",
    "ConversationBinding",
    "ConversationType",
    "CurrentSessionInspectionError",
    "CurrentSessionSnapshot",
    "EnvironmentFingerprint",
    "ExactHwndCaptureCapabilities",
    "ExactHwndReadonlyCapturePort",
    "FrontHalfAssessment",
    "FrontHalfNotReadyError",
    "FrontHalfStatus",
    "HumanBindingConfirmation",
    "IdentityBindingRegistry",
    "IdentityDisposition",
    "IdentityEvidenceSet",
    "IdentityReason",
    "IdentityResolution",
    "InMemoryObservationDedupStore",
    "LeaseAuditAction",
    "LeaseAuditEntry",
    "LeaseChallenge",
    "LeaseStatus",
    "LiveSessionScope",
    "MappingStatus",
    "ModalState",
    "NormalizedInboundEventCandidate",
    "ObservationBatch",
    "ObservationDedupPort",
    "ObservationDisposition",
    "ObservationIssue",
    "ObservationReason",
    "ProbeBridgeError",
    "ProfileIdentityError",
    "Q1SelectorPack",
    "QQCurrentChatCapturePort",
    "QQEnvironmentSentinel",
    "QQReadOnlyFrontHalf",
    "ReadonlyMessageObserver",
    "RoleCandidate",
    "RoleMapping",
    "RuntimeDecision",
    "RuntimeDecisionReason",
    "RuntimeEnvelope",
    "RuntimeSnapshot",
    "SelectorCompileResult",
    "SelectorRole",
    "SessionLease",
    "SessionLeaseError",
    "SessionLeaseManager",
    "SessionLeaseReason",
    "UiNodeInput",
    "UiNodeSnapshot",
    "UiTopologySnapshot",
    "UiaCaptureError",
    "UnsafeCapturePortError",
    "VisibleConversationSnapshot",
    "VisibleDirection",
    "VisibleMessage",
    "WindowBounds",
    "WindowPresentation",
    "assess_avatar_pending_application",
    "assess_binding_evidence",
    "assess_pending_application",
    "build_avatar_evidence",
    "build_identity_evidence",
    "compile_selector_pack",
    "ingest_probe_report",
    "invoke_current_session_helper",
    "map_role_candidates",
    "parse_avatar_report",
    "parse_current_session_report",
    "parse_profile_report",
]
