"""Q1: redacted UIA topology mapping and selector compilation.

This module consumes an injected, read-only representation of a UIA tree.  It
does not call Windows APIs and it never emits coordinates or input actions.
Names and other user supplied text are deliberately not retained in snapshots
or selector packs.
"""

from __future__ import annotations

import hashlib
import json
import math
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass
from enum import StrEnum


def _digest(value: object) -> str:
    encoded = json.dumps(
        value, ensure_ascii=False, sort_keys=True, separators=(",", ":")
    )
    return hashlib.sha256(encoded.encode("utf-8")).hexdigest()


def _clean(value: str) -> str:
    return " ".join(value.strip().lower().split())


class MappingStatus(StrEnum):
    UNIQUE = "unique"
    AMBIGUOUS = "ambiguous"
    NOT_FOUND = "not_found"
    REJECTED = "rejected"


class SelectorRole(StrEnum):
    MAIN_WINDOW = "main_window"
    CONVERSATION_LIST = "conversation_list"
    CONVERSATION_ITEM = "conversation_item"
    MESSAGE_REGION = "message_region"
    COMPOSER = "composer"
    SEND_BUTTON = "send_button"


@dataclass(frozen=True)
class UiNodeInput:
    """Read-only input from a UIA bridge.

    ``name`` is accepted only at the boundary and is never copied to output.
    ``semantic_anchors`` must be generated by a trusted local classifier (for
    example ``composer``); arbitrary visible text is not a selector signal.
    """

    runtime_id: str
    control_type: str
    class_name: str = ""
    automation_id: str | None = None
    name: str = ""
    patterns: tuple[str, ...] = ()
    parent_runtime_id: str | None = None
    semantic_anchors: tuple[str, ...] = ()
    normalized_rect: tuple[float, float, float, float] | None = None


RawUiNode = UiNodeInput


@dataclass(frozen=True)
class UiNodeSnapshot:
    """PII-minimized node record used for structural matching."""

    node_id: str
    parent_id: str | None
    control_type: str
    class_name: str
    patterns: tuple[str, ...]
    semantic_anchors: tuple[str, ...]
    normalized_rect: tuple[float, float, float, float] | None
    automation_id_digest: str | None

    @classmethod
    def from_input(cls, item: UiNodeInput) -> UiNodeSnapshot:
        if not item.runtime_id:
            raise ValueError("runtime_id is required")
        rect = _normalized_rect(item.normalized_rect)
        # The bridge's runtime id is opaque and hashed.  Keeping the same
        # derivation for parent references lets us use ancestor evidence while
        # never exposing a raw tree index or UIA id.
        stable_id = _digest({"runtime_id": item.runtime_id})
        parent_id = (
            _digest({"runtime_id": item.parent_runtime_id})
            if item.parent_runtime_id
            else None
        )
        anchors = tuple(
            sorted(
                {
                    _clean(anchor)
                    for anchor in item.semantic_anchors
                    if _clean(anchor)
                    in ({role.value for role in SelectorRole} | {"empty_chat_shell"})
                }
            )
        )
        return cls(
            node_id=stable_id,
            parent_id=parent_id,
            control_type=_clean(item.control_type),
            class_name=_clean(item.class_name),
            patterns=tuple(
                sorted({_clean(pattern) for pattern in item.patterns if pattern})
            ),
            semantic_anchors=anchors,
            normalized_rect=rect,
            automation_id_digest=(
                _digest({"automation_id": item.automation_id})
                if item.automation_id
                else None
            ),
        )


@dataclass(frozen=True)
class UiTopologySnapshot:
    client_version: str
    environment_fingerprint: str
    fixture_suite_version: str
    window_class_name: str
    window_handle: int
    nodes: tuple[UiNodeSnapshot, ...]
    tree_digest: str

    @classmethod
    def from_inputs(
        cls,
        nodes: Iterable[UiNodeInput],
        *,
        client_version: str,
        environment_fingerprint: str,
        fixture_suite_version: str,
        window_class_name: str = "",
        window_handle: int = 1,
    ) -> UiTopologySnapshot:
        snapshots = tuple(
            sorted(
                (UiNodeSnapshot.from_input(item) for item in nodes),
                key=lambda item: item.node_id,
            )
        )
        digest = _digest(
            {
                "client_version": client_version,
                "environment_fingerprint": environment_fingerprint,
                "fixture_suite_version": fixture_suite_version,
                "window_class_name": _clean(window_class_name),
                "nodes": [_node_payload(item) for item in snapshots],
            }
        )
        return cls(
            client_version=client_version,
            environment_fingerprint=environment_fingerprint,
            fixture_suite_version=fixture_suite_version,
            window_class_name=_clean(window_class_name),
            window_handle=window_handle,
            nodes=snapshots,
            tree_digest=digest,
        )


@dataclass(frozen=True)
class RoleCandidate:
    role: SelectorRole
    node_id: str
    score: float
    structural_score: float
    evidence: tuple[str, ...]


@dataclass(frozen=True)
class RoleMapping:
    role: SelectorRole
    status: MappingStatus
    candidates: tuple[RoleCandidate, ...]
    selected_node_id: str | None = None


@dataclass(frozen=True)
class CompiledSelector:
    """Executable lookup plus a runtime-id-free structural signature.

    ``node_id`` and ``ancestor_chain`` remain available to the current probe
    session, but neither participates in selector versioning.
    """

    role: SelectorRole
    node_id: str
    control_type: str
    patterns: tuple[str, ...]
    ancestor_chain: tuple[str, ...]
    score: float
    evidence: tuple[str, ...]
    class_name: str = ""
    semantic_anchors: tuple[str, ...] = ()
    normalized_rect: tuple[float, float, float, float] | None = None
    automation_id_digest: str | None = None
    ancestor_control_type_chain: tuple[str, ...] = ()

    @property
    def structural_signature(self) -> dict[str, object]:
        """Stable selector facts, excluding transient UIA runtime identity."""

        return {
            "role": self.role.value,
            "control_type": self.control_type,
            "class_name": self.class_name,
            "patterns": self.patterns,
            "semantic_anchors": self.semantic_anchors,
            "normalized_rect": self.normalized_rect,
            "automation_id_digest": self.automation_id_digest,
            "ancestor_control_type_chain": self.ancestor_control_type_chain,
        }


@dataclass(frozen=True)
class Q1SelectorPack:
    """A non-portable selector artifact bound to one exact topology context."""

    client_version: str
    environment_fingerprint: str
    topology_digest: str
    fixture_suite_version: str
    selectors: tuple[CompiledSelector, ...]

    def selector(self, role: SelectorRole | str) -> CompiledSelector:
        wanted = SelectorRole(role)
        matches = tuple(item for item in self.selectors if item.role is wanted)
        if len(matches) != 1:
            raise ValueError(f"selector {wanted.value!r} is absent or ambiguous")
        return matches[0]

    @property
    def structural_signatures(self) -> tuple[dict[str, object], ...]:
        """Canonical selected-role signatures used by downstream versioning."""

        return tuple(
            item.structural_signature
            for item in sorted(self.selectors, key=lambda value: value.role.value)
        )


@dataclass(frozen=True)
class SelectorCompileResult:
    status: MappingStatus
    mappings: tuple[RoleMapping, ...]
    pack: Q1SelectorPack | None = None

    @property
    def ambiguous_roles(self) -> tuple[SelectorRole, ...]:
        return tuple(
            item.role
            for item in self.mappings
            if item.status is MappingStatus.AMBIGUOUS
        )


_PATTERN_BY_ROLE: Mapping[SelectorRole, frozenset[str]] = {
    SelectorRole.CONVERSATION_LIST: frozenset(
        {"selectionpattern", "scrollpattern", "scrollitempattern"}
    ),
    SelectorRole.CONVERSATION_ITEM: frozenset(
        {"selectionitempattern", "invoke_pattern", "selectionpattern"}
    ),
    SelectorRole.MESSAGE_REGION: frozenset(
        {"textpattern", "documentpattern", "scrollpattern"}
    ),
    SelectorRole.COMPOSER: frozenset({"valuepattern", "textpattern"}),
    SelectorRole.SEND_BUTTON: frozenset({"invokepattern", "invoke_pattern"}),
}
_CONTROL_BY_ROLE: Mapping[SelectorRole, frozenset[str]] = {
    SelectorRole.MAIN_WINDOW: frozenset({"window"}),
    SelectorRole.CONVERSATION_LIST: frozenset({"list", "listbox", "tree", "table"}),
    SelectorRole.CONVERSATION_ITEM: frozenset({"listitem", "dataitem", "treeitem"}),
    SelectorRole.MESSAGE_REGION: frozenset({"document", "pane", "group"}),
    SelectorRole.COMPOSER: frozenset({"edit", "document"}),
    SelectorRole.SEND_BUTTON: frozenset({"button"}),
}
_MIN_STRUCTURAL_SCORE: Mapping[SelectorRole, float] = {
    SelectorRole.MAIN_WINDOW: 2,
    SelectorRole.CONVERSATION_LIST: 2,
    SelectorRole.CONVERSATION_ITEM: 2,
    SelectorRole.MESSAGE_REGION: 2,
    SelectorRole.COMPOSER: 3,
    SelectorRole.SEND_BUTTON: 3,
}


def _normalized_rect(
    value: tuple[float, float, float, float] | None,
) -> tuple[float, float, float, float] | None:
    if value is None:
        return None
    if len(value) != 4 or any(not math.isfinite(item) for item in value):
        raise ValueError("normalized_rect must contain four finite values")
    if any(item < 0 or item > 1 for item in value):
        raise ValueError("normalized_rect values must be between 0 and 1")
    left, top, right, bottom = value
    if right < left or bottom < top:
        raise ValueError("normalized_rect edges are not ordered")
    return tuple(round(item, 6) for item in value)


def _node_payload(node: UiNodeSnapshot) -> dict[str, object]:
    return {
        "node_id": node.node_id,
        "parent_id": node.parent_id,
        "control_type": node.control_type,
        "class_name": node.class_name,
        "patterns": node.patterns,
        "semantic_anchors": node.semantic_anchors,
        "normalized_rect": node.normalized_rect,
        "automation_id_digest": node.automation_id_digest,
    }


def _geometry_score(node: UiNodeSnapshot, role: SelectorRole) -> float:
    """Small layout prior only; it is never enough to pass a threshold."""
    if node.normalized_rect is None:
        return 0.0
    left, top, right, bottom = node.normalized_rect
    center_x = (left + right) / 2
    center_y = (top + bottom) / 2
    if role is SelectorRole.CONVERSATION_LIST and left < 0.45:
        return 0.25
    if role in {SelectorRole.COMPOSER, SelectorRole.SEND_BUTTON} and bottom > 0.65:
        return 0.25
    if role is SelectorRole.MESSAGE_REGION and center_x > 0.25:
        return 0.15
    if role is SelectorRole.MAIN_WINDOW and center_y > 0:
        return 0.05
    return 0.0


def _candidate(
    role: SelectorRole, node: UiNodeSnapshot, by_id: Mapping[str, UiNodeSnapshot]
) -> RoleCandidate:
    evidence: list[str] = []
    structural = 0.0
    if role.value in node.semantic_anchors:
        structural += 5
        evidence.append("semantic_anchor")
    if node.control_type in _CONTROL_BY_ROLE[role]:
        structural += 2
        evidence.append("control_type")
    matched_patterns = _PATTERN_BY_ROLE.get(role, frozenset()).intersection(
        node.patterns
    )
    if matched_patterns:
        structural += min(3, float(len(matched_patterns)))
        evidence.append("pattern_set")
    if node.parent_id and node.parent_id in by_id:
        parent = by_id[node.parent_id]
        if (
            role is SelectorRole.CONVERSATION_ITEM
            and parent.control_type in _CONTROL_BY_ROLE[SelectorRole.CONVERSATION_LIST]
        ):
            structural += 2
            evidence.append("ancestor_list")
        elif role is SelectorRole.COMPOSER and parent.control_type in {
            "pane",
            "window",
            "group",
        }:
            structural += 1
            evidence.append("ancestor_composer_container")
        elif role is SelectorRole.SEND_BUTTON and parent.control_type in {
            "pane",
            "group",
            "window",
        }:
            structural += 1
            evidence.append("ancestor_action_container")
    geometry = _geometry_score(node, role)
    if geometry:
        evidence.append("normalized_geometry")
    return RoleCandidate(
        role, node.node_id, structural + geometry, structural, tuple(evidence)
    )


def map_role_candidates(
    snapshot: UiTopologySnapshot,
    *,
    roles: Sequence[SelectorRole] = tuple(SelectorRole),
) -> tuple[RoleMapping, ...]:
    """Map roles using multiple signals; ties and weak candidates fail closed."""
    by_id = {node.node_id: node for node in snapshot.nodes}
    mappings: list[RoleMapping] = []
    anchored_roles = {
        anchor
        for node in snapshot.nodes
        for anchor in node.semantic_anchors
    }
    # QQ 9.9.33's observed empty-panel shell can otherwise let a broad Document
    # or Pane win through generic scoring and pretend that chat is readable.
    # Keep this guard version-bound and evidence-bound so selected chats and
    # older generic fixtures retain their independently classified region.
    message_region_requires_anchor = (
        snapshot.client_version.startswith("9.9.33.")
        and "empty_chat_shell" in anchored_roles
    )
    for role in roles:
        candidates = tuple(
            sorted(
                (_candidate(role, node, by_id) for node in snapshot.nodes),
                key=lambda item: (-item.score, item.node_id),
            )
        )
        viable = tuple(
            item
            for item in candidates
            if item.structural_score >= _MIN_STRUCTURAL_SCORE[role]
        )
        if role is SelectorRole.MESSAGE_REGION and message_region_requires_anchor:
            viable = ()
        if not viable:
            mappings.append(RoleMapping(role, MappingStatus.NOT_FOUND, candidates))
            continue
        best = viable[0]
        tied = tuple(
            item
            for item in viable
            if math.isclose(item.score, best.score, abs_tol=1e-9)
        )
        if len(tied) > 1:
            mappings.append(RoleMapping(role, MappingStatus.AMBIGUOUS, viable))
        else:
            mappings.append(
                RoleMapping(role, MappingStatus.UNIQUE, viable, best.node_id)
            )
    return tuple(mappings)


def compile_selector_pack(
    snapshot: UiTopologySnapshot,
    *,
    client_version: str | None = None,
    environment_fingerprint: str | None = None,
    fixture_suite_version: str | None = None,
    roles: Sequence[SelectorRole] = tuple(SelectorRole),
) -> SelectorCompileResult:
    """Compile a pack only when every requested role has one unique candidate."""
    if client_version is not None and client_version != snapshot.client_version:
        return SelectorCompileResult(MappingStatus.REJECTED, ())
    if (
        environment_fingerprint is not None
        and environment_fingerprint != snapshot.environment_fingerprint
    ):
        return SelectorCompileResult(MappingStatus.REJECTED, ())
    if (
        fixture_suite_version is not None
        and fixture_suite_version != snapshot.fixture_suite_version
    ):
        return SelectorCompileResult(MappingStatus.REJECTED, ())
    mappings = map_role_candidates(snapshot, roles=roles)
    if any(item.status is MappingStatus.AMBIGUOUS for item in mappings):
        return SelectorCompileResult(MappingStatus.AMBIGUOUS, mappings)
    if any(item.status is not MappingStatus.UNIQUE for item in mappings):
        return SelectorCompileResult(MappingStatus.NOT_FOUND, mappings)
    by_id = {node.node_id: node for node in snapshot.nodes}
    selectors = tuple(
        CompiledSelector(
            role=item.role,
            node_id=item.selected_node_id or "",
            control_type=by_id[item.selected_node_id or ""].control_type,
            class_name=by_id[item.selected_node_id or ""].class_name,
            patterns=by_id[item.selected_node_id or ""].patterns,
            semantic_anchors=by_id[item.selected_node_id or ""].semantic_anchors,
            normalized_rect=by_id[item.selected_node_id or ""].normalized_rect,
            automation_id_digest=by_id[
                item.selected_node_id or ""
            ].automation_id_digest,
            ancestor_chain=_ancestor_chain(by_id, item.selected_node_id or ""),
            ancestor_control_type_chain=_ancestor_control_type_chain(
                by_id, item.selected_node_id or ""
            ),
            score=item.candidates[0].score,
            evidence=item.candidates[0].evidence,
        )
        for item in mappings
    )
    selected_topology_digest = _digest(
        {
            "selectors": [
                item.structural_signature
                for item in sorted(selectors, key=lambda value: value.role.value)
            ]
        }
    )
    pack = Q1SelectorPack(
        client_version=snapshot.client_version,
        environment_fingerprint=snapshot.environment_fingerprint,
        topology_digest=selected_topology_digest,
        fixture_suite_version=snapshot.fixture_suite_version,
        selectors=selectors,
    )
    return SelectorCompileResult(MappingStatus.UNIQUE, mappings, pack)


def _ancestor_chain(
    by_id: Mapping[str, UiNodeSnapshot], node_id: str
) -> tuple[str, ...]:
    chain: list[str] = []
    current = by_id.get(node_id)
    seen: set[str] = set()
    while current and current.parent_id and current.parent_id not in seen:
        seen.add(current.parent_id)
        chain.append(current.parent_id)
        current = by_id.get(current.parent_id)
    return tuple(chain)


def _ancestor_control_type_chain(
    by_id: Mapping[str, UiNodeSnapshot], node_id: str
) -> tuple[str, ...]:
    chain: list[str] = []
    current = by_id.get(node_id)
    seen: set[str] = set()
    while current and current.parent_id and current.parent_id not in seen:
        seen.add(current.parent_id)
        current = by_id.get(current.parent_id)
        if current is not None:
            chain.append(current.control_type)
    return tuple(chain)


__all__ = [
    "CompiledSelector",
    "MappingStatus",
    "Q1SelectorPack",
    "RawUiNode",
    "RoleCandidate",
    "RoleMapping",
    "SelectorCompileResult",
    "SelectorRole",
    "UiNodeInput",
    "UiNodeSnapshot",
    "UiTopologySnapshot",
    "compile_selector_pack",
    "map_role_candidates",
]
